# Generated by Django 5.2.16 on 2026-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontent',
            name='platform',
            field=models.CharField(choices=[('Post', 'Post'), ('Caption', 'Caption'), ('Ad Copy', 'Ad Copy'), ('Story', 'Story'), ('Email', 'Email'), ('Video Script', 'Video Script')], max_length=50),
        ),
    ]
