# Generated by Django 5.2.16 on 2026-07-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaigncontent_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontent',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('TikTok', 'TikTok'), ('LinkedIn', 'LinkedIn'), ('Google Ads', 'Google Ads'), ('Email', 'Email'), ('Other', 'Other')], max_length=50),
        ),
    ]
