# Generated by Django 5.2.16 on 2026-07-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_campaign_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontent',
            name='language',
            field=models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English')], default='Arabic', max_length=20),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='language',
            field=models.CharField(default='Arabic', max_length=20),
        ),
    ]
