# Generated by Django 5.2.16 on 2026-09-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaigncontent_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontent',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_posters/'),
        ),
    ]
