# Generated by Django 5.2.16 on 2026-09-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaigncontent_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontent',
            name='instagram_media_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='instagram_permalink',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='publish_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
