# Generated by Django 5.2.16 on 2026-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_campaigncontent_instagram_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignperformance',
            name='external_post_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='impressions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='reach',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='saves',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='social_media_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='social_permalink',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='source',
            field=models.CharField(blank=True, choices=[('', 'Manual'), ('demo', 'Social demo'), ('live', 'Social live')], default='', max_length=20),
        ),
    ]
